# -*- coding: utf-8 -*-
"""tetanic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UDakgS-cWe1yTLT81NoagXG6mbhIa49f

## Poin Assignment :
**1.** Lakukan investigasi pada kondisi berikut :
- 1a. Lakukan pengecekan pada kolom mana yang terdapat data continue di dataframe ? (20 poin)
- 1b. Lakukan pengecekan pada kolom mana yang terdapat jenis kategorikal serta Uraikan juga jenis kategorikalnya termasuk kategorikal apa di masing-masing kolom dataframe ? (20 poin)

**2.** Looping
- `for` loop : print semua nama kolom yang ada pada file `titanic.xlsx` yang hanya dimulai dengan huruf konsonan (15 poin)
- `while` loop : print semua angka ganjil hingga `30`. Jika angka ganjil habis dibagi 3, print `"angka ini habis dibagi 3"` (15 poin)

**3** Lakukan manipulasi data `titanic.xlsx` menggunakan `lambda function` sesuai perintah dibawah ini :
1. Hitung jumlah missing value (NaN) pada kolom `body` (15)
2. Ubah female menjadi `0` dan male menjadi `1` pada kolom `sex` (15)

### Note : soal 1,2,3 menggunakan file titanic.csv
"""

import pandas as pd
data = pd.read_excel('/content/titanic.xlsx') # file excel
data.head()

data.info()

# 1. Infestigasi pada kondisi:
## 1a. Pengecekan kolom yang terdapat data continue di dataframe
data_continu = data.select_dtypes(include=['int64','float64'])
print(data_continu)

"""Berasarkan output, dapat melihat bahwa kolom 'pclass', 'survived', 'age',  'sibsp', 'parch', 'fare' dan 'body' memiliki tipe data numerik (int64 dan float64) sehingga kemungkinan besar berisi data kontinu."""

## 1b. Pengecekan kolom yang terdapat data kategorikal
data_category = data.select_dtypes(include=['object', 'category'])
print(data_category)

"""Berasarkan output, dapat melihat bahwa kolom ''name', 'sex', 'ticket', 'cabin', 'embarked', 'boat' dan'home.dest' memiliki tipe data kategorik.

Data kategorikal merupakan jenis data yang dapat dibagi menjadi beberapa kategori atau kelompok. Ada dua jenis utama data kategorikal: nominal dan ordinal. Data nominal tidak memiliki urutan, sementara data ordinal memiliki urutan atau peringkat.

Pada kolom data yang termasuk dalam data kategorik nominal adalah kolom 'name','sex', 'embarked' dan 'home.dest'. Sedangkan yang termasuk dalam data kategorik ordinal adalah 'ticket','cabin' dan 'boat'.

"""

# 2. Looping
## 2a. for loop : print semua nama kolom yang ada pada file titanic.xlsx yang hanya dimulai dengan huruf konsonan
def print_kolom_konsonan(data):
    """
    Mencetak nama kolom pada file yang dimulai dengan huruf konsonan.

    Args:
        file_path (str): Path ke file CSV.
    """
    try:
        df = pd.read_excel('/content/titanic.xlsx')
        for kolom in df.columns:
            if kolom[0].lower() not in 'aiueo':
                print(kolom)
    except FileNotFoundError:
        print(f"Error: File tidak ditemukan pada path: {df}")
    except pd.errors.EmptyDataError:
        print(f"Error: File kosong atau tidak ada data pada: {df}")
    except Exception as e:
        print(f"Terjadi kesalahan: {e}")


# Contoh penggunaan:
file_path = 'titanic.xlsx'  # Ganti dengan path file Anda
print_kolom_konsonan(file_path)

## 2b. while loop : print semua angka ganjil hingga 30. Jika angka ganjil habis dibagi 3, print "angka ini habis dibagi 3"
angka = 1
while angka <= 30:
    if angka % 2 != 0:
        print(angka, end=" ")
        if angka % 3 == 0:
            print("angka ini habis dibagi 3")
        else:
           print() # Pindah baris
    angka += 1

# 3. Manipulasi data titanic.xlsx menggunakan lambda function
## 3a. Jumlah missing value (NaN) pada kolom body
body = data['body'].isna().sum()
print(f"Jumlah missing values pada kolom body: {body}")

## 3b. Ubah female menjadi 0 dan male menjadi 1 pada kolom sex
from sklearn.preprocessing import LabelEncoder

labelencoder = LabelEncoder()
gender = data['sex'].replace({"female": 0, "male": 1})
data['sex'] = labelencoder.fit_transform(gender)
print(data['sex'])